### ISSUE TITLE
/usr/local/bin/burrito: line 33: `ascii-burrito': not a valid identifier

### ISSUE THREAD

**Issue by bigardone** [jasonreece/css-burrito#2]
Hi!
Im trying to setup burrito in a new project but I get this error while executing _burrito -n_:

```
/usr/local/bin/burrito: line 33: `ascii-burrito': not a valid identifier
```

Any ideas of what might be wrong?

Thanks in advance!

**Comment by endoze** [comment]
@bigardone Are you by chance using Zsh as your shell? I ran into this same issue. I resolved it by switching to bash before running the `burrito -n` command. In order to fix the actual issue however, I think adding a shebang at the top of the `burrito.sh` might fix this issue.

**Comment by endoze** [comment]
@bigardone I've created #3 to fix this issue.

**Comment by bigardone** [comment]
Hi! Yes, I'm using Zsh. I have installed the latest version of css-burrito and I still get this error :(

**Comment by endoze** [comment]
@bigardone It doesn't look like my pull request has been merged. You can either manually edit the script on your local machine or clone down my fork and use the branch with the fix.

**Comment by jasonreece** [comment]
Sorry folks, just realized I wan't getting notifications on this repo...

Just merged.

Thanks @endoze!

**Comment by endoze** [comment]
@jasonreece Thanks for the merge. Awesome template by the way!
